project_id = "lmjqgntpchoqknwrnurt"

[functions.reset-user-password]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.extract-document-id]
verify_jwt = false

[functions.reverse-geocode]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.place-details]
verify_jwt = false

[functions.geofence-alert]
verify_jwt = false
